### ISSUE TITLE
how to launched Terminal-Portable in path environment variable with wt

### ISSUE THREAD

**Issue by candrapersada** [asheroto/Terminal-Portable#3]

**Comment by asheroto** [comment]
If you open the EXE in WinRAR, you'll see a comment section describing where it extracts:

```
;The comment below contains SFX script commands

Path=%temp%\Terminal-Portable
SavePath
Setup="%temp%\Terminal-Portable\Terminal\wt.exe"
Presetup=rmdir "%temp%\Terminal-Portable" /s /q
Silent=1
Overwrite=1
```

In this case, you could use something like `"%temp%\Terminal-Portable\Terminal\wt.exe" -d C:\`, in `conhost.exe`, for example.

**Comment by asheroto** [comment]
You would have to run it at least once so it would extract.

There's nothing fancy about this EXE though, it's simply just the Terminal ZIP file with the `.portable` file included. Same exact thing as from here: https://github.com/microsoft/terminal/releases

![image](https://github.com/user-attachments/assets/952b27b8-47f2-4663-bf1c-e6db8cbf851b)
